apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-server
  ports:
    - protocol: TCP
      port: 8010      # Use port 80 to connect with INGRESS!
      targetPort: 8010
